### PR TITLE
feat(toast): support two lines label in Toast

### LINKED ISSUE #16: Important message in Toast is cut if the message is long
It happens that the important message in Toast is cut out when the message is longer than the toast width. So we would like to solve this problem in some way. 

- add tooltips to the overflow text ??
- allow multiple lines ??

image

### PR DESCRIPTION
**Pull request by boilund**
Closes #16

two-row-label

### CODE REVIEW

**Comment by anius** [comment]
Can the code be a mixin that is reused in `HeaderTitle` in `packages/core/src/Dialog/Dialog.tsx` as well? Something like this:

```tsx
const twoLinesClamp = styled.css`
  /* stylelint-disable-next-line value-no-vendor-prefix */
  display: -webkit-box;
  /* stylelint-disable-next-line property-no-vendor-prefix */
  -webkit-line-clamp: 2;
  /* stylelint-disable-next-line property-no-vendor-prefix */
  -webkit-box-orient: vertical;
  /* stylelint-disable-next-line property-no-vendor-prefix */
  -moz-box-orient: vertical;
  overflow: hidden;
  white-space: pre-wrap;
`

...
export const ToastLabel = styled(Typography).attrs({
  variant: 'chip-tag-text',	  variant: 'chip-tag-text',
})<{	})<{
  readonly hasCloseButton: boolean	  readonly hasCloseButton: boolean
  readonly isError: boolean	  readonly isError: boolean
  readonly hasEmphasis: boolean	  readonly hasEmphasis: boolean
}>`	}>`
  height: 100%;	  height: 100%;
  ${twoLinesClamp};
  ...
```

This way we will have `stylelint-disable-next-line` only in one file.

**Comment by anius** [comment]
Suggestions:

- More descriptive name than `twoLinesStyle `
- A comment with a description above for intellisense info in VS Code
-  `twoLinesStyle ` is exported in `index.ts` file so it could be imported from `practical-react-components-core` and reused in the application

**Comment by boilund** [comment]
> Suggestions:
> 
> * More descriptive name than `twoLinesStyle `
> * A comment with a description above for intellisense info in VS Code
> * `twoLinesStyle ` is exported in `index.ts` file so it could be imported from `practical-react-components-core` and reused in the application

Fixed all your suggestions. Changed the name to your original suggestion `twoLinesClamp` because the css property name is `line-clamp`. @anius

**Review by lekoaf — APPROVED** [review]
LGTM

**Comment by anius** [comment]
Suggestion:
```
/**
 * A styled-components mixin that truncates two-lines text with ellipsis.
 * 
 * An example:
 * ```tsx
 * const Div = styled.div`
 *   ${twoLinesClamp};
 * `
 * ```
 */
```

or similar

**Pull request merged**
